disabled_rules:
  - identifier_name #允許非駝峰式的命名
  - trailing_whitespace #允許換行時產生的空白
  
line_length:
  warning: 160
  error: 300
  ignores_function_declarations: true
file_length:
  warning: 1000
  error: 1500
function_body_length:
  warning: 100
  error: 150
type_body_length:
  warning: 800
  error: 1200
